### ISSUE TITLE
 '0.parentNode' is null or not an object while using elem attribute

### ISSUE THREAD

**Issue by mrigess** [gilmoreorless/jquery-dom-line#3]
if i leave elem attribute, then line draws in between the points but since it draws multiple lines I have this necessity to add elem attribute. Works fine in demo scripts but my app utilises jquery 1.7.2 and it gives this warning in console.

 '0.parentNode' is null or not an object

**Comment by gilmoreorless** [comment]
Hi, I'm having trouble reproducing this.

Do you have an example script that shows the error? Either something on your site, or jsfiddle.net / jsbin.com
Does it only happen in one browser, or all browsers?

Cheers,
Gil

**Comment by gilmoreorless** [comment]
Actually, I've worked out the cause - if the `elem` option is provided, but it's an empty jQuery object (e.g. `$('#does-not-exist')`) this error is thrown.

I'll fix up the script to not fail in this case.

**Comment by mrigess** [comment]
thanks for making this update available :)
